### ISSUE TITLE
 Already managing a GoogleApiClient with id 0

### ISSUE THREAD

**Issue by ZaydelEduard** [pavel163/SocialAuth#1]
Hello. Crash with        java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0,
after try to integrate your lib to my project. Everything is done as on this activity https://github.com/pavel163/SocialAuth/blob/master/app/src/main/java/com/ebr163/socialauth/GooglePlusActivity.java,  Stackoverflow recommend use this code http://stackoverflow.com/questions/36105118/already-managing-a-googleapiclient-with-id-0-in-fragment , i look at your source code, you have such method, named "free" but it's unused method.

**Comment by pavel163** [comment]
version 1.0.2. 
`@Override
    protected void onDestroy() {
        super.onDestroy();
        googlePlusClient.free();
    }`
