### ISSUE TITLE
Hardcored Facebook Permissions 

### ISSUE THREAD

**Issue by ZaydelEduard** [pavel163/SocialAuth#2]
Can you make permissions of facebook modifiable? 
now we have 
this.facebookPermissions = Arrays.asList(new String[]{"public_profile", "email", "user_birthday", "user_friends"});

need somithing like this 
facebookClient.setRequestedPermission(new String[] or ArrayList<String>)

**Comment by pavel163** [comment]
thank you for the feedback. fix in 1.0.3
