### ISSUE TITLE
Constructors call twice

### ISSUE THREAD

**Issue by ZaydelEduard** [pavel163/SocialAuth#3]
If we will use this code in fragment 
        googlePlusClient = new GooglePlusClient(this);

will call     public GooglePlusClient(Fragment fragment) { 
and after this will be call     public GooglePlusClient(Activity activity) {
as conclusion init method will call twice and will be crashed with

java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0 

---------------------------

we can fix this crash if change      googlePlusClient = new GooglePlusClient(this); to      googlePlusClient = new GooglePlusClient(getActivity); (only activity constructor will be call) , but method onActivityResult call in activity class, not in fragment.

**Comment by ZaydelEduard** [comment]
Can be fixed if change googlePlusClient = new GooglePlusClient(this) to googlePlusClient = new GooglePlusClient(getActivity()); (will be call only activity constructor)

**Comment by pavel163** [comment]
Thank you for the feedback. Fix in 1.0.3
